### ISSUE TITLE
Les publications ne s'affichent pas dans les mots-clés cochés

### ISSUE THREAD

**Issue by AnneLHuet** [Chartes-TNAH/flux#145]
Je viens de voir que les publications entrées (pas celles de nos données test) ne s'affiche pas correctement dans les mots-clés !

**Comment by algaudin** [comment]
Par contre, les publications, lorsqu'on les affiche par mots-clés, ne sont pas classés par ordre de date :) Si vous voulez, je m'en charge ? :)

**Comment by FMezard** [comment]
Je veux bien, merci !
