### ISSUE TITLE
Modification des conditions pour inscription

### ISSUE THREAD

**Issue by algaudin** [Chartes-TNAH/flux#154]
Suite au commentaire de @Keyuteotter  dans #60 , je peux modifier si vous le voulez, pour afficher un message d'erreur si la promo est inférieure à 2006 et limiter le choix des spécialités :)

**Comment by FMezard** [comment]
@algaudin : Ca lance une `ValueError` si on ne mets pas de date d'inscription !

**Comment by algaudin** [comment]
Ah, merci ! Je vais corriger cette erreur au plus vite ! :)
