### ISSUE TITLE
Affichage / design

### ISSUE THREAD

**Issue by FMezard** [Chartes-TNAH/flux#159]
Notre site n'est vraiment pas du tout responsive :S (même sur mon écran ça ne marche pas très bien ! )

**Comment by FMezard** [comment]
Il faudrait aussi rajouter des marges un peu partout, pour plus de clarte

**Comment by FMezard** [comment]
Il y a un probleme d'affichage des boutons sous Chrome

**Comment by algaudin** [comment]
On avait pas des marges avant ?

**Comment by FMezard** [comment]
Si, en fait je crois que le probleme c'est qu'on a tout fait sur firefox et que ca ne marche pas sous chrome (j'ai pas encore essaye Safari, mais je sens que ca va etre sympa aussi ^^)

**Comment by mggourio** [comment]
Je viens de tester PythouNews sous Chrome -> tout est nickel, et je n'ai pas eu de problème d'affichage de boutons ! Seules les marges ne se font pas.

**Comment by FMezard** [comment]
Moi j'ai ca : 
![screen shot 2018-04-11 at 1 14 05 pm](https://user-images.githubusercontent.com/29238793/38632283-3c0bb11e-3d8a-11e8-963e-800c2480c72e.png)

**Comment by algaudin** [comment]
Même sous Firefox, les marges ont disparues

**Comment by mggourio** [comment]
Pourtant, quant je teste, que ce soit sous mozilla ou sous chrome, les boutons sont en vert. @FMezard  tu es sous safari ?
Est-ce c'est la mise sur serveur qui aurait pu faire disparaître les marges ?
Et avez-vous vu que le lien du flux INHA ne marche plus ? (en tout cas plus sous chrome et mozilla)

**Comment by FMezard** [comment]
Non, je suis sous chrome (mais avec un mac, je ne sais pas si ca change quoi que ce soit) et le lien INHA marche chez moi ^^. Les marges ne sont pas la non plus si tu lances en local il me semble, il va falloir jeter un coup d'oeil au css.

**Comment by FMezard** [comment]
C'est bon, j'ai trouvé ! C'est parce qu'il y avait marqué `type="button"` à la place de `role="button"`, je pense juste que firefox était sympa et nous a pas embêté, mais ça ne marchait pas sur tout du coup (ça ne marchait pas sur safari non plus).
