### ISSUE TITLE
Ou trouver les données des flux ? 

### ISSUE THREAD

**Issue by FMezard** [Chartes-TNAH/flux#22]
Résultat du brainstorming : 

Je mets tout en vrac, à trier par la suite, n'hésitez pas à  rajouter vos propositions
Il faudra par la suite proposer des options de tris, car il va y avoir bcp de ressources. 

Comptes twitter (à voir comment il est possible de les récupérer automatiquement)

- Gauthier Poupeau
- Thibault Clérice 
- Johanna Daniels 
- Ecole des chartes 
- Ademec 
- #DH

Sites : 

- Ademec 
- Emplois 
    - Biblioemplois 
    - ProfessionArchiviste 
    - Musées-emplois
- AAF 
- INHA
- 3 flux pour la BnF 
    - Actu culturelle 
    - Actu des bibliothèques 
    - Actu professionnel

**Comment by HeathcoteA** [comment]
Pour le moment, les flux rss qui posent problème sont ceux de l'Ademec (ils ont une page RSS mais qui ne fonctionne pas '404') et de l'INHA (ils mettent une image, ce qui nous bloque pour le moment).
