### ISSUE TITLE
Intégrer des flux RSS

### ISSUE THREAD

**Issue by algaudin** [Chartes-TNAH/flux#25]
Avec @AnneLHuet, nous avons commencé à regarder comment intégrer les flux RSS sur la page d'accueil. On a fait des tests avec le flux de l'école des chartes, voici le résultat : 
![fluxrss](https://user-images.githubusercontent.com/33345655/36726039-a2ada4d4-1bb8-11e8-850c-d5c2e81ed8fc.png)

Suivant le cours sur les fichiers csv, qui présentait un modèle de fonction de récupération des flux, on a modifié le fichier routes.py ainsi : 

```python
from feedparser import parse
@app.route("/")
def accueil():
    address="http://www.chartes.psl.eu/fr/rss"
    feed = parse(address)
    for item in feed["items"]:
        line = (
                item["title_detail"]["value"],
                    item["summary_detail"]["value"],
                    item["link"],
                    item["published"]
                )
    return render_template("pages/accueil.html", line=line)
```

On a également modifié la page accueil.html, en ajoutant un `{{line}}`

On pensait faire un module spécifique contenant la fonction, pour éviter la répéter pour chaque adresse. Voilà :)

**Comment by algaudin** [comment]
J'ai réussi à afficher plus proprement un élément du flux rss sur la page d'accueil : 
![propre](https://user-images.githubusercontent.com/33345655/36734984-60cdbe38-1bd5-11e8-8f86-51c09d11f30a.png)

Et tout cela en faisant simplement appel à la fonction dans la route : 
```
@app.route("/")
def accueil():
    titre, sujet, lien, date = flux_rss.read_rss("http://www.chartes.psl.eu/fr/rss")
    return render_template("pages/accueil.html", titre=titre, sujet=sujet, lien=lien, date=date)
```
J'ai également modifié la page accueil.html : 
```
<p>{{titre}}</br>
    {{sujet}}</br>
    <a href="{{lien}}">Lien vers la page</a></br>
    {{date}}
  </p>
```

Toutefois, cela ne permet d'afficher qu'un seul élément d'un unique flux rss. Il ne permet pas la généralisation à plusieurs flux rss. Mais on est sur la bonne voie ;)

**Comment by AnneLHuet** [comment]
On a fait une branche issue-25 sur laquelle on va travailler tous les trois (il faut veiller à travailler sur une autre branche que issue-25 pour éviter les conflits). On fera donc une pull request quand on sera un peu plus avancé puisque pour l'instant on teste beaucoup de choses =) 
Le mieux étant de nommer les nouvelles branches en fonction de nos modifications, il faudrait nous répartir ce qu'il y a à faire : 
de ce que je vois il faut : 
* trouver une solution pour que le code dans route soit simplifié
* modifier la fonction read_rss pour pouvoir intégrer également les images (le problème se pose sur le flux rss de l'INHA)
* créer une autre fonction pour l'affichage des pages twitter (?)
* un travail sur la page html accueil (et éventuellement réflechir à si on aurait pas besoin d'une page dédiée, selon ce que l'on définit dans l'issue #22 dédiée aux choix des flux rss

Est-ce que vous pensez à autre chose ?

**Comment by algaudin** [comment]
Si vous voulez, je peux me charger de simplifier le code. Je n'hésiterai pas à faire appel à vous si j'ai un souci ;)

**Comment by algaudin** [comment]
J'ai tenté de simplifier le code, sans succès. Je souhaitais intégrer directement du html dans la fonction python, histoire que l'affichage se fasse plus aisément sur la page de titre, mais les balises n'étaient pas interprétées, et étaient affichées telles quelles. 
J'ai tenté d'introduire des expressions régulières dans le code, mais là aussi, ce fut un échec. Cette fois-ci les caractères tels que `\n` n'étaient plus présents sur la page d'accueil, pour autant ils n'étaient pas non plus interprétés. 
Je n'ai pas trouvé d'autre solution plus simple pour l'instant, mais je ne désespère pas trouver un jour une solution :)

**Comment by HeathcoteA** [comment]
Après une réflexion concertée, on a établi qu'il serait plus judicieux de créer une table Flux afin de récupérer les derniers flux rss et les insérer dans une méthode static : appeler directement depuis la table SQL (comme les utilisateurs) paraît préférable.
