### ISSUE TITLE
Pages des profils

### ISSUE THREAD

**Issue by mggourio** [Chartes-TNAH/flux#26]
C'est parti pour la création des pages profils des utilisateurs ! 
Chaque page profil permettrait l'affichage de la photo de l'utilisateur, ses infos et un bouton "éditer" le profil accessible au seul propriétaire du profil. Et la photo par défaut = le python à lunettes d'@HeathcoteA  !

**Comment by FMezard** [comment]
Je continue la page profil avec la possibilité pour l'utilisateur de l'éditer
