### ISSUE TITLE
Propositions de logo !

### ISSUE THREAD

**Issue by HeathcoteA** [Chartes-TNAH/flux#27]
Voici quelques logos élaborés à partir d'éléments libres de droit pour notre application de flux PythouNews. 

Votez ! :)

1. ![1](https://user-images.githubusercontent.com/33458861/36742378-cc0035f2-1be7-11e8-8c28-0b56c5012e31.jpg)

2. ![2](https://user-images.githubusercontent.com/33458861/36742379-cc18d9a4-1be7-11e8-8ebe-a6fb6358da2d.jpg)

3. ![3](https://user-images.githubusercontent.com/33458861/36742380-cc4a6122-1be7-11e8-8ec6-a0c89ca6bd4f.jpg)

4. ![4](https://user-images.githubusercontent.com/33458861/36742381-cc631500-1be7-11e8-878a-911818023ac2.jpg)

5. ![5](https://user-images.githubusercontent.com/33458861/36742382-cc801650-1be7-11e8-8822-471be573ef37.jpg)

6. ![6](https://user-images.githubusercontent.com/33458861/36742383-cc9d0cc4-1be7-11e8-90c8-d231d1c6328b.jpg)

7. ![7](https://user-images.githubusercontent.com/33458861/36742384-ccb7ca1e-1be7-11e8-918d-8dd305792561.jpg)

8. ![8](https://user-images.githubusercontent.com/33458861/36742385-ccd31ddc-1be7-11e8-9973-4c4107fdd788.jpg)

9. ![9](https://user-images.githubusercontent.com/33458861/36742386-ccef6410-1be7-11e8-8ef6-501c41b86739.jpg)

10. ![10](https://user-images.githubusercontent.com/33458861/36742387-cd08237e-1be7-11e8-8f3a-8ec19e66f62f.jpg)

11. ![11](https://user-images.githubusercontent.com/33458861/36742388-cd200d5e-1be7-11e8-8f8a-86deb411d315.jpg)

12. ![12](https://user-images.githubusercontent.com/33458861/36742389-cd3868ae-1be7-11e8-882c-7c2b2ba5a343.jpg)

13. ![13](https://user-images.githubusercontent.com/33458861/36742390-cd54f050-1be7-11e8-9836-4f61c07c5812.jpg)

14. ![14](https://user-images.githubusercontent.com/33458861/36742391-cd732be2-1be7-11e8-9a37-fc78c788545a.jpg)

**Comment by AnneLHuet** [comment]
Je vote pour le 2 comme logo ! Le premier je le vois bien affiché sur une  page d'erreur =)

**Comment by mggourio** [comment]
Je vote pour le 1 en logo !! 
Et je verrais bien le serpent à lunettes tout seul pour les photos de profil par défaut, et le 12 pour l'erreur 404.

**Comment by algaudin** [comment]
Je vote pour le 2 comme logo. Le serpent seul pour les photos de profil par défaut, c'est une excellente idée ! :) 
Par contre, je verrais bien le 14 sur la page d'erreur.

**Comment by FMezard** [comment]
Je vote aussi pour le 14 en page d'erreur, le serpent tout seul en photo de profil. Comme logo, après discussion avec Léa, je propose le 6 sans le serpent qui entoure :) (ça revient au 2 mais avec `ythounews` derrière ^^).

**Comment by HeathcoteA** [comment]
Je suis ok pour le 'P-ythounews' en logo 🥇 
@AnneLHuet  et @algaudin, vous votiez pour le 2, je suppose que logo2+ythounews vous convient ? @mggourio  Je suis désolée, la sentence est irrévocable, ton esprit de contradiction est encore une fois éprouvé ^^

**Comment by mggourio** [comment]
Bon bah, je m'incline !
