### ISSUE TITLE
Répartition des rôles pour commencer le projet

### ISSUE THREAD

**Issue by FMezard** [Chartes-TNAH/flux#3]
# Répartition des rôles 1 : 

- About TNAH - @mggourio 
- Inscription - @Keyuteotter 
- Connexion - @HeathcoteA  
- Header - @AnneLHuet 
- Footer - @algaudin

**Comment by HeathcoteA** [comment]
La page connexion étant faite, je m'occupe de l'inscription :)

**Comment by FMezard** [comment]
Sorry !! Je le referai plus ^^
