### ISSUE TITLE
Création d'une page pour que les utilisateurs puissent partager du contenu

### ISSUE THREAD

**Issue by AnneLHuet** [Chartes-TNAH/flux#40]
J'ouvre une issue pour qu'on puisse travailler ensemble avec Amandine sur une page de publication pour nos utilisateurs =)

**Comment by FMezard** [comment]
J'ai regardé ce que tu as pushé sur issue-40 @AnneLHuet, pour le moment en lisant le code j'ai remarqué ça : 
`if len(erreurs) > 0: 
print("Votre publication n'a pas été validée car nous avons rencontré les erreurs suivantes :" + erreurs)`
Attention : le `print` sert à afficher dans la console, il faut trouver une autre façon de prévenir l'utilisateur

**Comment by HeathcoteA** [comment]
D'accord, merci d'avoir vérifié Fanny ! :)

**Comment by FMezard** [comment]
C'est bon, ça fonctionne ! :D Si vous êtes curieuses, je vous mets ce qu'il manquait (c'était vraiment pas grand chose !) : 

- Il manquait l'import du modèle `publication`dans les routes, c'est pour ça que l'erreur disait que la fonction n'existait pas. 
- J'ai changé le `print(erreurs)` par un `return` dans la méthode statique pour pouvoir récupérer et afficher les erreurs. 

Moral de l'histoire, les publications sont maintenant stockées dans la base SQL, reste à savoir qu'en faire :P 

Sinon pour le moment j'ai remplacé le format `date` par du texte dans la base de données, parce que l'utilisateur ne mettra jamais la date de lui-même au bon format et je ne sais pas comment le forcer ^^

**Comment by FMezard** [comment]
Il y a des choses à changer : 

- Prévenir l'utilisateur si le nom de publication est trop long (ou le texte)
- Changer `DATETIME` en `TEXT` dans le modèle SQL (avant de trouver une manière de remplir automatiquement le champ date)
