### ISSUE TITLE
Bilan et to do - list

### ISSUE THREAD

**Issue by FMezard** [Chartes-TNAH/flux#48]
- Débugguer le code pour les publications
- Ajouter les catégories pour les flux 
- Gérer les catégories pour les utilisateurs
- Beautiful soup
- Moteur de recherche 
- Pagination de la page d'accueil
- Limiter la taille des textes des flux dans l'affichage (avec `...`) 
- Réflexion sur l'expérience utilisateur : comment répartir les informations sur les différentes pages pour que ce soit clair ! 
- Recherche (avancée ?)
- Documentation
- Test ?? 
- Un petit peu de design peut être :) 
Choisissez votre mission en commentaire ! :)  (les tâches en haut de la liste sont les plus urgentes a priori, j'en ai probablement oublié plein, j'ai essayé de mettre ce qu'on avait dit pendant la réunion).

**Comment by algaudin** [comment]
A part si vous voulez changer, je veux bien continuer dans les flux rss  :)

**Comment by FMezard** [comment]
Je veux bien m'occuper des catégories pour les utilisateurs (une fois qu'on sera d'accord sur ce qu'on veut ^^).

**Comment by AnneLHuet** [comment]
Je veux bien débugguer pour les publications et faire beautiful soup =)

**Comment by mggourio** [comment]
Je veux bien gérer le moteur de recherche ;)

**Comment by HeathcoteA** [comment]
Je vais me renseigner pour ajouter des catégories aux flux !

**Comment by mggourio** [comment]
Chic, on avance !! On a fait toute la to do list !!
