### ISSUE TITLE
Catégories flux et publications

### ISSUE THREAD

**Issue by HeathcoteA** [Chartes-TNAH/flux#49]
Création d'une liste fermée de catégories pour séparer les flux par genre:
- Histoire de l'art 
- Archives
- Bibliothèques
- Emploi
- Recherches

**Comment by algaudin** [comment]
Ce que je vous propose pour le moment, c'est de créer une page par catégorie de flux, et d'inclure la catégorie directement quand on rentre un nouveau flux. Est-ce que ça vous va ?
