### ISSUE TITLE
Nom de l'application

### ISSUE THREAD

**Issue by mggourio** [Chartes-TNAH/flux#5]
Bonjour !!

Nous n'avons pas encore établi fermement le nom de notre futur flux d'informations !
Les idées en lice sont :
- Boactu
- BOA
- Pythounews ou PythouNews
- Fiat Lux ou FiatLUX
- The News-Actus Home
- Toutes Nouvelles Actus de l'Historien
- les Tigres Ne mAngent pas d'Herbes
- les masTers soNt extrAordinaires H
- ...
Quel nom emporte vos suffrages ? Avez-vous d'autres idées ?

**Comment by AnneLHuet** [comment]
Je vois qu'il y a eu pas mal de réflexion ! ;) J'ai une petite préférence pour PythouNews personnellement :)

**Comment by FMezard** [comment]
Moi aussi :P Mais j'ai rien contre les Toutes Nouvelles Actus de l'Historien si qqun pose son veto sur mon cher python ^^

**Comment by mggourio** [comment]
Je vois que vous avez abandonné Boactu, j'ai l'impression que je vais devoir m'incliner ! J'aime bien aussi les Toutes Nouvelles Actus de l'Historien, si c'est possible de s'opposer au cher python ;)

**Comment by mggourio** [comment]
Et sinon, Alix nous propose "boa de neuf ?" Qu'en pensez-vous ???

**Comment by algaudin** [comment]
PYTHOUNEWS !! :)

**Comment by mggourio** [comment]
Bon, je cède face à la force ! Va pour PythouNews...

**Comment by mggourio** [comment]
On invente un logo ???

**Comment by AnneLHuet** [comment]
J'allais en parler ! Quelqu'un a une inspiration ? On peut peut-être regarder sur les sites qui proposent des images libre de droit =)
