### ISSUE TITLE
Les balises apparaissent dans le texte des flux rss

### ISSUE THREAD

**Issue by FMezard** [Chartes-TNAH/flux#54]
La page d'accueil affiche bien les textes des flux RSS, mais aussi les balises. Après avoir vainement tenté plusieurs solutions, je pense tenter de les supprimer à l'aider d'une expression régulière, qui enlèverait tout ce qui est entre `<` et `>`. @algaudin ça te va ?

**Comment by FMezard** [comment]
J'AI TROUVE !!!!! Il faut rajouter un `|safe` après le nom de la variable dans la balise jinja, pour préciser que le HTML est à interpréter !! Pour l'école des chartes, ça donne `{{ sujet_chartes|safe }}`

**Comment by algaudin** [comment]
TROP BIEN ! Merci beaucoup !

**Comment by mggourio** [comment]
Géniiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiial !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
