### ISSUE TITLE
Pagination des pages publications et catégories des publications

### ISSUE THREAD

**Issue by mggourio** [Chartes-TNAH/flux#56]
Salut à vous !!

Je me lance dans la pagination de notre page d'accueil.

**Comment by mggourio** [comment]
Afin de paginer la page d'accueil qui affiche les flux rss, il est nécessaire que les flux soient intégrés dans notre base de données MySQL, ce qui n'est pas le cas pour l'instant.
@algaudin saurais-tu comment faire ? Sachant que la table des flux est faite. Merciiiii !

**Comment by algaudin** [comment]
Pour l'instant, on va intégrer des méthodes statiques à la suite de la table (histoire que ça évite d'encombrer routes ^^). Après je pense que ça sera plus simple de paginer ? :)

**Comment by mggourio** [comment]
Et bien je n'en sais rien !! Je testerai !!

**Comment by mggourio** [comment]
La page d'affichage de l'ensemble des publications est paginée, et ça fonctionne bien. Le hic, c'est que le code n'est pas bien propre et que les flux et les paginations par catégorie ne sont pas paginés.

**Comment by algaudin** [comment]
Du coup, est-ce que la pagination fonctionne aussi pour les pages qui regroupent les publications par catégories ? :)
