### ISSUE TITLE
Organisation du site et expérience utilisateur 

### ISSUE THREAD

**Issue by FMezard** [Chartes-TNAH/flux#59]
Après réflexion sur la gestion des différentes pages, nous proposons avec @mggourio et @algaudin, de faire : 
- une page d'accueil avec les flux et les billets les plus récents 
- une page publication avec la recherche à facette (et une pagination)
- une page flux RSS à peu près pareil

Qu'en pensez-vous ??

**Comment by AnneLHuet** [comment]
Ca me semble très bien !
