### ISSUE TITLE
Améliorations à apporter

### ISSUE THREAD

**Issue by algaudin** [Chartes-TNAH/flux#60]
Vous pourrez mettre ici toutes les améliorations à apporter à notre magnifique Pythounews ! 

Je commence la liste avec : 
- FAIT Une date automatique et non remplie par l'utilisateur

- FAIT Modification du texte du footer pour qu'il soit adapté à des fenêtres plus petites

N'hésitez pas  :)

**Comment by AnneLHuet** [comment]
@algaudin pour la date automatique c'est pour les publications des utilisateurs ? =)

**Comment by algaudin** [comment]
Oui :)

**Comment by FMezard** [comment]
- FAIT Changer le message d'erreur quand la promo n'est pas une date 
- FAIT Renvoyer vers la page connexion après l'inscription
- FAIT Uniformiser le html (balise `<!DOCTYPE html>`
- FAIT Ajouter des commentaires quand on affiche les éléments d'une liste (c'est très mystérieux sinon ^^)

**Comment by mggourio** [comment]
- FAIT le nom de l'utilisateur attaché automatiquement à sa publication
- FAIT  La gestion des colonnes bootstrap sur la page publications

**Comment by mggourio** [comment]
- FAIT enlever les print de débuggage dans nos codes !
- PRESQUE FINI commenter notre code

**Comment by algaudin** [comment]
FAIT Pour la date automatique, il ne faudrait pas mettre `default=datetime.datetime.utcnow` quand on définit la date dans la classe ?

**Comment by mggourio** [comment]
- FAIT Avec BeautifulSoup, il est possible de récupérer automatique le titre du lien partagé par les utilisateurs. La zone titre du formulaire de publication devient donc inutile à partir du moment où BS est activé ! + récupération automatique de l'auteur de la publication et de la date. Ce qui nous donnera un formulaire de publication avec une zone titre, une zone lien et une zone commentaire
- FAIT Faire un requirements.txt !!
- FAIT écrire la documentation dans le README.md

**Comment by mggourio** [comment]
- FAIT sur la page publications de PythouNews, il faut réussir à récupérer seulement la valeur de l'attribut `content` de la balise `meta` (le code se trouve dans le fichier publication.py).

**Comment by mggourio** [comment]
- FAIT qu'un utilisateur puisse consulter la page profil des autres utilisateurs

**Comment by mggourio** [comment]
- FAIT attention, quand il n'y a pas de publications, les catégories ne marchent pas

**Comment by algaudin** [comment]
- FAIT Qu'il n'y est que 2 flux rss sur la page d'accueil

- FAIT Modifier la fonction d'affichage des flux rss sur la page rss.html, parce que là, c'est pas très propre

- FAIT Afficher les pages de catégories de flux même quand on est pas connecté

**Comment by mggourio** [comment]
- FAIT sur la page des publications, il faut que le "none" ne s'affiche pas quand la page html de l'url ne contient pas de description.
- FAIT afficher les 2 dernières publications sur la page d'accueil

**Comment by algaudin** [comment]
-  FAIT Afficher des messages en Flash pour signaler que l'utilisateur doit s'identifier pour accéder à la page 

- FAIT Quand une publication est effectuée, faire retourner l'utilisateur sur la page qui contient l'ensemble des publications

- FAIT Uniformiser l'affichage de la page "toutes les publications" et "publication par catégories", avec l'affichage des boutons aussi dans les publications par catégories 

- FAIT Faire en sorte que les liens des publications s'affichent et soient cliquables, dans les pages par catégories de publications

**Comment by mggourio** [comment]
- FAIT améliorer le code de la pagination (dans les fichiers routes.py, publication.py, afficherpublis.html et fichiers similaires pour les flux rss)

**Comment by mggourio** [comment]
- FAIT Yalaaaaayouhouuuuu !! Le moteur de recherche fonctionne !! Il affiche en résultats le titre de la publication, et le seul hic, c'est qu'il ne cherche que dans le titre de la publication alors qu'il faudrait qu'il cherche dans le titre et le commentaire.
- FAIT Et le 2ème hic du moteur de recherche, c'est qu'une fois qu'on a les résultats, les liens vers les publications ne marchent pas. Mais sinon tout va bien :)

**Comment by algaudin** [comment]
- FAIT Penser à changer la catégorie des flux "Archives" et "Musée", parce que pour l'instant, c'est inversé :)

**Comment by algaudin** [comment]
FAIT Si l'envie vous prend, vous pouvez ajouter plus de fils d'actus twitter :) (Parce que j'ai supprimé Poupeau pour y mettre Ecole Royale des Chartres, suite à ce qu'on avait dit ^^)

**Comment by FMezard** [comment]
- FAIT Ranger le code en ordonnant les routes  par soucis de visibilité

**Comment by algaudin** [comment]
- FAIT Ajouter un bouton supplémentaire pour la catégorie "Numérique"

- NON Faire en sorte que les boutons se mettent en vert lorsqu'on sélectionne une catégorie (de publication ou de flux)

**Comment by mggourio** [comment]
- FAIT Lorsqu'on veut modifier son profil, le message `Les erreurs suivantes ont été rencontrées : Le nom est obligatoire,L'email est obligatoire,Le login est obligatoire` s'affiche.
- FAIT faire une jolie présentation pour les résultats de la recherche
- FAIT que les publications de l'utilisateur s'affichent lorsqu'on se rend sur le profil de cet utilisateur
- FAIT changer le bouton de la page profil.html de "Modifier le profil" en "Modifier mon profil" ?
- FAIT le lien du footer "Publications" mène à la page du formulaire de publication. Que pensez-vous de faire qu'il mène à la page de toutes les publications, et de rajouter dans ce footer un lien "Flux" qui permettrait d'aller vers la page de tous les flux ?

**Comment by mggourio** [comment]
- faire une jolie présentation pour les résultats de la recherche

**Comment by mggourio** [comment]
- que les publications de l'utilisateur s'affichent lorsqu'on se rend sur le profil de cet utilisateur

**Comment by mggourio** [comment]
- changer le bouton de la page profil.html de "Modifier le profil" en "Modifier mon profil" ?

**Comment by mggourio** [comment]
- le lien du footer "Publications" mène à la page du formulaire de publication. Que pensez-vous de faire qu'il mène à la page de toutes le publications, et de rajouter dans ce footer un lien "Flux" qui permettrait d'aaler vers la page de tous les flux ?

**Comment by algaudin** [comment]
- Il n'y a pas de pagination lorsque l'on consulte les publications par catégories (idem pour les flux rss)

**Comment by FMezard** [comment]
- FAIT (hormis nouvelles idées) Il faut ajouter des tests sur ce que rentre l'utilisateur (la promo est comprise entre 2000 et 2030, les spécialités à gérer avec des checkbox et pas une entrée libre de l'utilisateur ... j'en oublie surement plein)

**Comment by FMezard** [comment]
Tout est fait sauf la pagination des publications ! Je declare cette issue fermee, les ameliorations pourront etre faites dans d'autres issues, les points importants sont regles !
