### ISSUE TITLE
Ajout des flux RSS à la base SQL et adaptation du code pour les afficher

### ISSUE THREAD

**Issue by FMezard** [Chartes-TNAH/flux#62]

**Comment by FMezard** [comment]
4h après, ça a l'air de marcher ! Merci @algaudin  pour ta patience :P

**Comment by algaudin** [comment]
De rien, on ne va pas se cacher que c'est quand même plus "Python Zen" ainsi ^^

**Comment by FMezard** [comment]
Il faudra penser à enlever le `i=0` qui ne nous a pas servi !
