### ISSUE TITLE
Récupérer les <meta name="description" /> et <title /> des url

### ISSUE THREAD

**Issue by AnneLHuet** [Chartes-TNAH/flux#63]
Je propose de modifier le code avec Beautiful Soup pour que l'application récupère les informations `<meta name="description" />`  et `<title/>` des pages partagées par les utilisateurs.

**Comment by AnneLHuet** [comment]
Avec @mggourio nous avons fait un exemple de l'utilisation de Beautiful Soup, pour bien comprendre son utilisation, que l'on va intégrer à notre code 
```python
from bs4 import BeautifulSoup
import requests

html = requests.get('https://www.fabula.org/actualites/l-impressionnisme-face-aux-idees_82285.php')

html_doc = html.text
text = BeautifulSoup(html_doc, 'html.parser')
description = text.find_all("meta", attrs={"name":u"description"})
title = text.title
print(title)
print(description)
```

**Comment by mggourio** [comment]
Chouette, comme ça on a notre code sous les yeux !!
C'est parti pour l'intégration de BS dans notre code !!

**Comment by AnneLHuet** [comment]
Je laisse cette issue ouverte car il nous reste le problème des balises <meta/> qui s'affiche sur notre page !

**Comment by FMezard** [comment]
Je mets ça là en attendant d'avoir le temps de regarder, je l'ai trouvé sur [Lien](http://apprendre-python.com/page-beautifulsoup-html-parser-python-library-xml). C'est pour récupérer les attributs normalement 

```python
from bs4 import BeautifulSoup

html_doc = """
<html>
    <head>
    <title>Titre de votre site</title>
    </head>
    <body>
        <p class="c1 c2">Texte à lire 1</p>
        <p class="c3">Texte à lire 2</p>
    </body>
</html>
"""
soup = BeautifulSoup(html_doc)
    
for p in soup.find_all('p'):
    print p.get("class")
```

**Comment by AnneLHuet** [comment]
@Keyuteotter je me repenche sur cette question ! =)
