### ISSUE TITLE
Gestion des utilisateurs

### ISSUE THREAD

**Issue by FMezard** [Chartes-TNAH/flux#7]
Je suis en train de créer la page connexion, pour inclure le header et le footer j'ai mis : 

- @AnneLHuet : `{% include "partial/header.html" %}`
- @algaudin  : `{% include "partial/footer.html" %}`

Dites-moi si vous avez nommés vos fichiers autrement ou s'ils ne sont pas dans ce dossier.

**Comment by algaudin** [comment]
Je n'ai pas encore nommé mon fichier pour le footer, mais je ne sais plus si, pour Boatlas, les fichiers types conteneurs se trouvaient dans le dossier partial ?

**Comment by FMezard** [comment]
Je ne pense pas que le footer soit un conteneur. J'essaie de m'expliquer : on ne va pas intégrer le code de `connexion.html` dans le code de  `footer.html` mais on va faire le contraire : intégrer le `footer.html`et le  `header.html` dans chacun des fichiers `connexion.html` etc. Du coup, si j'ai bien compris, il faut bien les ranger dans le dossier `partials`.

**Comment by algaudin** [comment]
Au temps pour moi,  j'ai tout confondu à la fois ^^

**Comment by mggourio** [comment]
Coucou,

Je pense que l'erreur sur laquelle on tombe :
`sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'pythounews_user'@'localhost' (using password: YES)") (Background on this error at: http://sqlalche.me/e/e3q8)`
indique que l'utilisateur n'a pas le droit de se connecter (`Access denied for user`). A mon avis (et selon @HeathcoteA qui m'a soufflé l'idée...!) c'est parce qu'il manque une passerelle entre notre base de donnée Mysql et notre site. Du coup, lors de l'inscription l'utilisateur tente de se connecter à notre base de données, alors qu'il doit se connecter au site, d'où `Access denied for user`.

Alors, pour régler ce sac de noeuds, il faudrait juste créer la passerelle. (bon, j'en conviens, c'est plus facile à dire qu'à faire ! Mais l'on peut sûrement s'inpirer de Boatlas...) On regarde ça et on se dit quoi ?

**Comment by FMezard** [comment]
Coucou ! 

Nous avions simplement oublié de créer un utilisateur mysql pour accéder à cette base de données. Je l'ai fait pour moi, mais il va falloir que vous le fassiez chacun sur votre ordinateur. Plutôt que de me lancer dans un tuto, nous pourrons le faire ensemble à la prochaine réunion ! 
Du coup ça marche sur mon ordi, alors je vais pusher :) 

Dans le code j'ai juste eu à changer cette ligne `app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://pythounews:pythounews@localhost/pythounews'` avec le 1er pythounews comme nom d'utilisateur, le deuxième comme mot de passe et le troisième comme nom de la base de donnée utilisateur (oui, j'ai un peu abusé sur les `pythounews`, je m'en excuse !)

**Comment by FMezard** [comment]
Un jour j'y arriverai, c'était encore pas bon !!
